# Generated by Django 4.1.7 on 2023-03-12 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_task_avancement_task_avancement_reel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_de_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 1, 48, 9, 530429)),
        ),
    ]
