# Generated by Django 4.1.7 on 2023-03-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_task_date_de_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_suppression',
        ),
    ]
