# Generated by Django 4.1.7 on 2023-03-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_conversation_message_conversation_last_message_and_more'),
        ('project', '0009_remove_task_date_suppression'),
    ]

    operations = [
    ]
