# Generated by Django 4.1.7 on 2023-03-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_merge_20230312_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
